// src/lib/themes.ts
// Theme colors and display labels.
//
// The "official" lab themes (energy-systems, land-use, trade, impacts) get
// curated palette assignments — these are the themes with dedicated
// /research/<slug> pages. Any other theme slug that appears in the
// Publications sheet gets a deterministic Spectral color picked by hashing
// the slug, and a label generated by titlecasing the slug. Add a new theme
// to the sheet → it shows up correctly on the site without any code change.

export const THEME_COLORS: Record<string, string> = {
  'energy-systems': 'var(--spectral-3)',  // orange-red
  'land-use':       'var(--spectral-9)',  // green
  'trade':          'var(--spectral-10)', // blue
  'impacts':        'var(--spectral-2)',  // red
}

export const THEME_LABELS: Record<string, string> = {
  'energy-systems': 'Energy systems',
  'land-use':       'Land use',
  'trade':          'Trade',
  'impacts':        'Impacts',
}

// Spectral indices unused by the curated themes that still have legible
// contrast on the cream paper background. Skips 5 (yellow) and 6 (pale
// yellow), which are too light for text and thin borders.
const DYNAMIC_PALETTE_INDICES = [11, 1, 4, 8, 7]

function hashSlug(slug: string): number {
  let h = 0
  for (let i = 0; i < slug.length; i++) {
    h = ((h << 5) - h) + slug.charCodeAt(i)
    h |= 0
  }
  return Math.abs(h)
}

/** Color for a theme slug. Curated themes get their assigned palette color;
 *  any other slug gets a deterministic Spectral color (stable across builds
 *  because it's a pure function of the slug). */
export function themeColor(slug: string): string {
  if (slug in THEME_COLORS) return THEME_COLORS[slug]
  const idx = DYNAMIC_PALETTE_INDICES[hashSlug(slug) % DYNAMIC_PALETTE_INDICES.length]
  return `var(--spectral-${idx})`
}

/** Display label for a theme slug. Curated themes use their hand-written
 *  label; any other slug is titlecased ("climate-change" → "Climate change",
 *  "co2_removal" → "Co2 removal"). */
export function themeLabel(slug: string): string {
  if (slug in THEME_LABELS) return THEME_LABELS[slug]
  return slug
    .replace(/[-_]+/g, ' ')
    .replace(/^./, (c) => c.toUpperCase())
}
